# Generated by Django 4.0.4 on 2022-05-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
