# Generated by Django 4.0.4 on 2022-05-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryblog', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
