# Generated by Django 4.0.4 on 2022-05-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryblog', '0003_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото поста'),
            preserve_default=False,
        ),
    ]
