# Generated by Django 4.0.4 on 2022-05-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryblog', '0004_post_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_text',
        ),
    ]
