# Generated by Django 4.0.4 on 2022-05-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryblog', '0005_remove_post_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_text',
            field=models.CharField(default=111, max_length=50, verbose_name='Підзаголовок'),
            preserve_default=False,
        ),
    ]
